application-message:
  success-code : 0
  success-text: Operation successful
  #-------------------------------------------------------------------#
  message-not-send-code : 1001
  message-not-send-text: Send message fail
  #-------------------------------------------------------------------#
  duplicate-exchange-code : 1002
  duplicate-exchange-text: Douplicate Name
  #-------------------------------------------------------------------#
  not-exist-code : 1003
  not-exist-text: This record does not exist
  #-------------------------------------------------------------------#
  username-telegram-null-code : 1004
  username-telegram-null-text: Please change your username
  #-------------------------------------------------------------------#
  send-telegram-bot-fail-code : 1005
  send-telegram-bot-fail-text: Send Message fail
  #-------------------------------------------------------------------#
  telegram-bot-username-null-code : 1005
  telegram-bot-username-null-text: Test - Please change telegram username and restart this bot again
  #-------------------------------------------------------------------#
  validation-error-code: 400
  validation-error-text:  is missing!
  #-------------------------------------------------------------------#
  unknown-error-code: 9999
  unknown-error-text: Please try again
